image: python:3.9
cache:
  key: dependencies
  paths:
    - .cache/pip/
    - .venv
before_script:
  - python --version
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv
test:
  script:
    - poetry run py.test -vvxra --tb=short --cov=website_app --cov-report=term-missing tests